---
- name: check for wireguard_vpn_ip
  ansible.builtin.assert:
    that:
      - wireguard_vpn_ip is defined
      - wireguard_vpn_ip | ansible.utils.ipaddr == wireguard_vpn_ip

- name: main | install wireguard
  ansible.builtin.include_tasks: "install.yml"

- name: main | configure wireguard
  ansible.builtin.include_tasks: "config.yml"

- name: main | enable wireguard service
  ansible.builtin.service:
    name: "wg-quick@{{ wireguard_network_name }}"
    state: started
    enabled: yes
  when: not ansible_check_mode

- name: main | configure static resolution for wireguard addresses
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} WIREGUARD MANAGED BLOCK"
    block: |
      {{ wireguard_vpn_ip }} {{ inventory_hostname }}.{{ wireguard_hosts_domain }}
      {% for host in wireguard_network.get(inventory_hostname, []) | sort %}
      {{ hostvars[host]['wireguard_vpn_ip'] }} {{ host }}.{{ wireguard_hosts_domain }} {{ host }}
      {% endfor %}
  when: wireguard_hosts_enabled|bool
