---
- name: check for wireguard_vpn_ip
  ansible.builtin.assert:
    that:
      - wireguard_vpn_ip | ansible.utils.ipaddr == wireguard_vpn_ip

- name: main | install wireguard
  ansible.builtin.include_tasks: "install.yml"

- name: main | configure wireguard
  ansible.builtin.include_tasks: "config.yml"

- name: main | enable wireguard service
  ansible.builtin.service:
    name: "wg-quick@{{ wireguard_network_name }}"
    state: started
    enabled: yes
