---
- name: converge
  hosts: all
  vars:
    wireguard_network:
      node1:
        - node2
        - node3
      node2:
        - node1
      node3:
        - node1
    wireguard_hosts_enabled: true
    wireguard_hosts_domain: 'localdomain'
  roles:
    - role: oukooveu.wireguard
